[build-system]
requires = ["setuptools>=61.0"]
build-backend = "setuptools.build_meta"

[project]
name = "YoutubePlaylistDownloader"
version = "0.1.0"
description = "Outil Python pour télécharger une playlist YouTube avec choix de qualité"
readme = "README.md"
requires-python = ">=3.7"
license = {text = "MIT"}
authors = [
  {name = "TonNom", email = "ton@email.com"}
]
dependencies = [
  "yt-dlp>=2024.3.10"
]


[tool.setuptools.packages.find]
include = ["youtube_downloader"]

[project.scripts]
yt-download = "main:main"
